(()=>{
'use strict';
const LEVELS={
1:{rows:9,cols:9,mines:10,goal:3},
2:{rows:9,cols:9,mines:15,goal:4},
3:{rows:10,cols:10,mines:20,goal:4},
4:{rows:12,cols:12,mines:25,goal:4},
5:{rows:14,cols:14,mines:35,goal:4},
6:{rows:16,cols:16,mines:40,goal:4},
7:{rows:16,cols:20,mines:60,goal:3},
8:{rows:16,cols:30,mines:99,goal:2}
};
const LIMIT=10*60*1000,REWARD=100;
const board=document.getElementById('arenaBoard'),status=document.getElementById('arenaStatus'),ticketCount=document.getElementById('arenaTicketCount'),timeLeft=document.getElementById('arenaTimeLeft'),clearEl=document.getElementById('arenaClearCount'),view=document.getElementById('arenaView');
if(!board||!status||!view)return;
const oldStart=document.getElementById('arenaStartBtn'),startBtn=oldStart.cloneNode(true);oldStart.replaceWith(startBtn);
let level=1,cfg=LEVELS[1],grid=[],boardStarted=false,boardOver=true,active=false,deadline=0,timer=null,clears=0,boardTickets=0,locked=false;
const getLang=()=>{try{return currentLang==='en'?'en':'ko'}catch(_){return'ko'}};
const tx=(ko,en)=>getLang()==='en'?en:ko;
const style=document.createElement('style');style.textContent='.arena-levels{display:grid;grid-template-columns:repeat(4,minmax(110px,1fr));gap:8px;margin:12px 0}.arena-level-btn{padding:10px 8px;border:1px solid #d1d5db;border-radius:10px;background:#fff;font-weight:800;cursor:pointer}.arena-level-btn.active{background:#111827;color:#fff;border-color:#111827}.arena-level-btn:disabled{opacity:.55;cursor:not-allowed}.arena-challenge-summary{padding:10px 12px;border:1px solid #d1d5db;border-radius:10px;background:#fff;margin:8px 0;line-height:1.55}@media(max-width:700px){.arena-levels{grid-template-columns:repeat(2,minmax(110px,1fr))}}';document.head.appendChild(style);
const panel=view.querySelector('.arena-panel'),desc=panel?.querySelector('.mode-desc'),toolbar=panel?.querySelector('.arena-toolbar');
const levelBox=document.createElement('div');levelBox.className='arena-levels';levelBox.id='arenaLevelPicker';
for(let lv=1;lv<=8;lv++){const b=document.createElement('button');b.type='button';b.className='arena-level-btn';b.dataset.level=lv;b.onclick=()=>{if(active)return;level=lv;cfg=LEVELS[lv];renderTexts();resetBoard(false);status.textContent=tx(`${lv}레벨을 선택했어. 티켓 1개로 시작해!`,`Level ${lv} selected. Start with 1 ticket!`)};levelBox.appendChild(b)}
toolbar?.parentNode?.insertBefore(levelBox,toolbar);
const summary=document.createElement('div');summary.className='arena-challenge-summary';levelBox.after(summary);
function renderTexts(){cfg=LEVELS[level];document.querySelectorAll('.arena-level-btn').forEach(b=>{const lv=+b.dataset.level,c=LEVELS[lv];b.textContent=tx(`⚔️ ${lv}레벨`,`⚔️ Level ${lv}`)+` · ${c.cols}×${c.rows} / ${c.mines}`;b.classList.toggle('active',lv===level);b.disabled=active});if(desc)desc.textContent=tx('레벨을 고르고 🎟️ 티켓 1개로 10분 도전! 제한시간 안에 목표 판 수를 클리어하면 성공해. 지뢰를 눌러도 그 판만 끝나고, 시간이 남아 있으면 새 판이 바로 시작돼.','Choose a level and spend 1 🎟️ ticket for a 10-minute challenge. Clear the target number of boards to win. Hitting a mine ends only that board; if time remains, a new board starts automatically.');summary.textContent=tx(`${level}레벨 · ${cfg.cols}×${cfg.rows} · 지뢰 ${cfg.mines}개 · 목표 ${cfg.goal}판 · 제한시간 10분`,`Level ${level} · ${cfg.cols}×${cfg.rows} · ${cfg.mines} mines · Goal ${cfg.goal} boards · 10 minutes`);startBtn.textContent=tx('🎟️ 티켓 1개로 시작','🎟️ Start with 1 ticket');const info=document.getElementById('arenaInfo');if(info)info.textContent=tx('안전칸마다 1% 확률로 🎟️ 티켓을 얻을 수 있어. 지뢰를 누르면 그 판만 실패하고 시간이 남으면 새 판이 시작돼. 10분이 끝났을 때 이미 진행 중인 판은 끝까지 할 수 있지만, 그 판이 끝난 뒤에는 새 판을 시작할 수 없어. 마지막 진행 판으로 목표 수를 채워도 성공이야.','Each safe cell has a 1% chance to award a 🎟️ ticket. A mine fails only that board and another starts if time remains. If 10 minutes expires during an active board, you may finish that board, but no new board can start afterward. Completing the target on that final board still counts as success.');if(!active)timeLeft.textContent='10:00'}
try{FULL_TEXT.ko.arenaInfo='안전칸마다 1% 확률로 🎟️ 투기장 티켓을 얻을 수 있습니다. 지뢰를 누르면 그 판만 종료되고 시간이 남으면 새 판이 시작됩니다. 10분이 끝났을 때 이미 진행 중인 판은 끝까지 할 수 있지만 그 뒤에는 새 판이 시작되지 않습니다.';FULL_TEXT.en.arenaInfo='Each safe cell has a 1% chance to award a 🎟️ Arena Ticket. A mine ends only that board and another starts if time remains. If the 10-minute timer expires during an active board, you may finish that board, but no new board starts afterward.'}catch(_){}
try{const m=document.querySelectorAll('.arena-profile-card .asset-mini');if(m[1])m[1].innerHTML=`<span>${tx('투기장','Arena')}</span><b>${tx('1~8레벨','Levels 1–8')}</b>`;if(m[2])m[2].innerHTML=`<span>${tx('규칙','Rule')}</span><b>${tx('10분 도전','10-min challenge')}</b>`}catch(_){}
function ns(r,c){const a=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const nr=r+dr,nc=c+dc;if(nr>=0&&nr<cfg.rows&&nc>=0&&nc<cfg.cols)a.push([nr,nc])}return a}
function render(r,c){const x=grid[r][c],e=x.el,t=e.classList.contains('arena-ticket-cell');e.className='cell';if(t)e.classList.add('arena-ticket-cell');e.textContent='';if(x.open){e.classList.add('open');if(x.mine)e.textContent='💣';else if(x.num){e.textContent=x.num;e.classList.add('n'+x.num)}}else if(x.flag){e.classList.add('flag');e.textContent='🚩'}}
function resetBoard(mark=true){cfg=LEVELS[level];boardTickets=0;boardStarted=false;boardOver=false;locked=false;grid=Array.from({length:cfg.rows},()=>Array.from({length:cfg.cols},()=>({mine:false,open:false,flag:false,num:0,el:null})));board.innerHTML='';board.style.gridTemplateColumns=`repeat(${cfg.cols},30px)`;for(let r=0;r<cfg.rows;r++)for(let c=0;c<cfg.cols;c++){const e=document.createElement('button');e.type='button';e.className='cell';e.onclick=()=>openCell(r,c);e.oncontextmenu=ev=>{ev.preventDefault();flag(r,c)};grid[r][c].el=e;board.appendChild(e)}try{arenaGrid=grid;arenaStarted=false;arenaOver=false;arenaPaid=active;arenaClearCount=clears}catch(_){}if(mark&&active){try{heartbeat('playing','arena')}catch(_){}publish(false)}}
function plant(sr,sc){const ban=new Set([`${sr},${sc}`]);ns(sr,sc).forEach(([r,c])=>ban.add(`${r},${c}`));const cand=[];for(let r=0;r<cfg.rows;r++)for(let c=0;c<cfg.cols;c++)if(!ban.has(`${r},${c}`))cand.push([r,c]);for(let i=cand.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cand[i],cand[j]]=[cand[j],cand[i]]}for(let i=0;i<Math.min(cfg.mines,cand.length);i++){const[r,c]=cand[i];grid[r][c].mine=true}for(let r=0;r<cfg.rows;r++)for(let c=0;c<cfg.cols;c++)if(!grid[r][c].mine)grid[r][c].num=ns(r,c).filter(([a,b])=>grid[a][b].mine).length}
async function ticketRoll(r,c){try{if(!sb||!currentUser)return;const use=ticketTestMode&&isChocopieTestAccount(),{data,error}=await sb.rpc(use?'arena_cell_reward_test':'arena_cell_reward');if(error)return;if(data?.ticket_awarded){boardTickets++;grid[r][c].el.classList.add('arena-ticket-cell');await syncOnlineState();refreshArenaWallet();refreshMarket()}}catch(_){}}
function reveal(r,c){const x=grid[r][c];if(x.open||x.flag||x.mine)return;x.open=true;render(r,c);ticketRoll(r,c)}
function flood(r,c){const q=[[r,c]],seen=new Set([`${r},${c}`]);while(q.length){const[cr,cc]=q.pop();for(const[nr,nc]of ns(cr,cc)){const y=grid[nr][nc];if(!y.open&&!y.flag&&!y.mine){reveal(nr,nc);if(y.num===0&&!seen.has(`${nr},${nc}`)){seen.add(`${nr},${nc}`);q.push([nr,nc])}}}}}
function openCell(r,c){if(!active||boardOver||locked)return;const x=grid[r][c];if(x.open&&!x.mine&&x.num>0){chord(r,c);return}if(x.open||x.flag)return;if(!boardStarted&&Date.now()>=deadline){finish(false,tx('⏰ 시간이 끝나 새 판을 시작할 수 없어.','⏰ Time is up; no new board can start.'));return}if(!boardStarted){boardStarted=true;plant(r,c);try{arenaStarted=true;heartbeat('playing','arena')}catch(_){}}if(x.mine){mine(r,c);return}reveal(r,c);if(x.num===0)flood(r,c);winCheck();publish(false)}
function chord(r,c){if(!active||boardOver||locked)return;const x=grid[r][c];if(!x.open||x.mine||x.num<=0)return;const n=ns(r,c),f=n.filter(([a,b])=>grid[a][b].flag).length;if(f!==x.num)return;for(const[nr,nc]of n){if(boardOver)break;const y=grid[nr][nc];if(!y.open&&!y.flag)openCell(nr,nc)}publish(false)}
function flag(r,c){if(!active||boardOver||locked)return;const x=grid[r][c];if(x.open)return;x.flag=!x.flag;render(r,c);publish(false)}
function revealMines(){for(let r=0;r<cfg.rows;r++)for(let c=0;c<cfg.cols;c++){const x=grid[r][c];if(x.mine&&!x.open){x.open=true;render(r,c)}}}
function mine(r,c){if(locked)return;locked=true;const x=grid[r][c];x.open=true;render(r,c);x.el.textContent='💥';x.el.classList.add('boom');boardOver=true;revealMines();publish(true);const expired=Date.now()>=deadline;status.textContent=expired?tx(`💥 지뢰! 마지막 진행 판 종료. ${clears}/${cfg.goal}판 클리어.`,`💥 Mine! Final active board ended. ${clears}/${cfg.goal} cleared.`):tx(`💥 지뢰! 이 판만 실패. 새 판 시작! (${clears}/${cfg.goal})`,`💥 Mine! Only this board failed. New board starting! (${clears}/${cfg.goal})`);if(expired)setTimeout(()=>finish(false),650);else setTimeout(()=>{if(!active)return;resetBoard(true);status.textContent=tx(`⚔️ ${level}레벨 새 판! ${clears}/${cfg.goal}판`,`⚔️ Level ${level}, new board! ${clears}/${cfg.goal}`)},650)}
async function winCheck(){if(boardOver||locked)return;let closed=0;for(let r=0;r<cfg.rows;r++)for(let c=0;c<cfg.cols;c++)if(!grid[r][c].mine&&!grid[r][c].open)closed++;if(closed)return;locked=true;boardOver=true;for(let r=0;r<cfg.rows;r++)for(let c=0;c<cfg.cols;c++){const x=grid[r][c];if(x.mine&&!x.flag){x.flag=true;render(r,c)}}let rewarded=false;try{if(sb&&currentUser){const{error}=await sb.rpc('arena_win_reward');if(!error){rewarded=true;await syncOnlineState();refreshProfile();refreshMarket()}}}catch(_){}clears++;clearEl.textContent=clears;try{arenaClearCount=clears}catch(_){}publish(true);if(clears>=cfg.goal){finish(true,tx(`🏆 ${level}레벨 클리어! 목표 ${cfg.goal}판 달성!${rewarded?` · 판당 ${REWARD}코인`:''}`,`🏆 Level ${level} cleared! Target ${cfg.goal} reached!${rewarded?` · ${REWARD} coins per clear`:''}`));return}if(Date.now()>=deadline){status.textContent=tx(`🏆 마지막 판 클리어! 현재 ${clears}/${cfg.goal}판.`,`🏆 Final board cleared! ${clears}/${cfg.goal}.`);setTimeout(()=>finish(false),750);return}status.textContent=tx(`🏆 클리어! ${clears}/${cfg.goal} · 다음 판 시작`,`🏆 Clear! ${clears}/${cfg.goal} · Next board`);setTimeout(()=>{if(!active)return;resetBoard(true);status.textContent=tx(`⚔️ ${level}레벨 · ${clears}/${cfg.goal}판`,`⚔️ Level ${level} · ${clears}/${cfg.goal}`)},450)}
function fmt(ms){const s=Math.max(0,Math.ceil(ms/1000));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function tick(){if(!active)return;const left=deadline-Date.now();timeLeft.textContent=fmt(left);if(left>0)return;timeLeft.textContent='00:00';if(boardStarted&&!boardOver){status.textContent=tx(`⏰ 10분 종료! 현재 진행 중인 판은 끝까지 할 수 있어. ${clears}/${cfg.goal}판.`,`⏰ 10 minutes are up! Finish this active board. ${clears}/${cfg.goal}.`);clearInterval(timer);timer=null}else finish(false,tx(`⏰ 시간 종료! ${clears}/${cfg.goal}판 클리어.`,`⏰ Time up! ${clears}/${cfg.goal} cleared.`))}
function controls(dis){document.querySelectorAll('.arena-level-btn').forEach(b=>b.disabled=dis);startBtn.disabled=dis}
function finish(success,msg=''){if(!active)return;active=false;boardOver=true;locked=false;clearInterval(timer);timer=null;if(Date.now()>=deadline)timeLeft.textContent='00:00';controls(false);status.textContent=msg||[tx(`⏰ ${level}레벨 도전 종료 · ${clears}/${cfg.goal}판`,`⏰ Level ${level} challenge ended · ${clears}/${cfg.goal}`),tx(`🏆 ${level}레벨 도전 성공! ${clears}/${cfg.goal}판`,`🏆 Level ${level} complete! ${clears}/${cfg.goal}`)][success?1:0];try{arenaSessionActive=false;arenaPaid=false;arenaOver=true;arenaStarted=false;heartbeat('online',null);scheduleLivePublish('arena',true)}catch(_){}wallet()}
function wallet(){try{refreshArenaWallet()}catch(_){try{ticketCount.textContent=Number(getTradeAssets().ticket||0)}catch(_){}}}
function publish(done){try{scheduleLivePublish('arena',!!done)}catch(_){}}
try{arenaSnapshot=function(){return{mode:'arena',label:`투기장 ${level}레벨 ${cfg.cols}×${cfg.rows} · 지뢰 ${cfg.mines}`,rows:cfg.rows,cols:cfg.cols,cells:grid.map(row=>row.map(x=>({open:!!x.open,flag:!!x.flag,value:x.open?(x.mine?'mine':x.num):null,ticket:!!x.el?.classList.contains('arena-ticket-cell')})))}}}catch(_){}
startBtn.addEventListener('click',async()=>{if(active)return;try{if(!sb||!currentUser){status.textContent=tx('로그인 후 투기장을 시작할 수 있어.','Log in to start the Arena.');return}startBtn.disabled=true;const{error}=await sb.rpc('arena_enter');if(error){startBtn.disabled=false;status.textContent=String(error.message||'').toLowerCase().includes('ticket')?tx('🎟️ 투기장 티켓이 부족해.','🎟️ Not enough Arena Tickets.'):tx(`입장 실패: ${error.message}`,`Entry failed: ${error.message}`);return}cfg=LEVELS[level];active=true;deadline=Date.now()+LIMIT;clears=0;clearEl.textContent='0';timeLeft.textContent='10:00';controls(true);try{arenaSessionActive=true;arenaDeadline=deadline;arenaPaid=true}catch(_){}resetBoard(true);status.textContent=tx(`⚔️ ${level}레벨 시작! 10분 안에 ${cfg.goal}판 클리어. 첫 클릭과 주변 칸은 안전해.`,`⚔️ Level ${level} started! Clear ${cfg.goal} boards in 10 minutes. First click and surrounding cells are safe.`);clearInterval(timer);timer=setInterval(tick,250);tick();await syncOnlineState();wallet();refreshMarket()}catch(e){startBtn.disabled=false;status.textContent=tx(`입장 실패: ${e?.message||e}`,`Entry failed: ${e?.message||e}`)}});
document.querySelectorAll('.lang-switch button').forEach(b=>b.addEventListener('click',()=>setTimeout(renderTexts,0)));
renderTexts();resetBoard(false);boardOver=true;status.textContent=tx('레벨을 선택하고 티켓 1개로 시작해!','Choose a level and start with 1 ticket!');wallet();
})();
