(()=>{
'use strict';
const KEY='msSuiteV3';
let match=null,aiTimer=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(_){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('mso-state-changed'))}
function norm(s){s.lp=Number(s.lp||0);s.mmr=Number(s.mmr||1000);s.pvp??={wins:0,losses:0};s.pvpExtreme??={wins:0,losses:0};return s}
function style(){if(document.getElementById('xpvpStyle'))return;const x=document.createElement('style');x.id='xpvpStyle';x.textContent=`.xpvp-wrap{margin-top:14px}.xpvp-top{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:8px 0}.xpvp-score{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.xpvp-panel{border:1px solid #dbe3ec;border-radius:12px;background:#fff;padding:12px}.xpvp-board{display:grid;grid-template-columns:repeat(9,24px);gap:2px;width:max-content;max-width:100%;margin-top:8px}.xpvp-cell{width:24px;height:24px;padding:0;border:1px solid #b8c1cc;border-radius:3px;background:#dbe3ec;font-size:12px;font-weight:900;cursor:pointer}.xpvp-cell.open{background:#fff}.xpvp-cell.blocked{background:#111827;color:#fff;cursor:not-allowed}.xpvp-cell.mine{background:#ef4444;color:#fff}.xpvp-feed{margin-top:8px;min-height:22px;font-weight:800}.xpvp-meter{height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden}.xpvp-meter i{display:block;height:100%;background:#111827}.xpvp-opponent .xpvp-cell{pointer-events:none}@media(max-width:700px){.xpvp-score{grid-template-columns:1fr}.xpvp-board{grid-template-columns:repeat(9,22px)}.xpvp-cell{width:22px;height:22px}}`;document.head.appendChild(x)}
function makeBoard(){const cells=Array.from({length:81},(_,i)=>({mine:false,open:false,blocked:false,num:0,i}));const mines=[];while(mines.length<10){const n=Math.floor(Math.random()*81);if(!mines.includes(n))mines.push(n)}mines.forEach(i=>cells[i].mine=true);for(let i=0;i<81;i++){if(cells[i].mine)continue;const r=Math.floor(i/9),c=i%9;let n=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const rr=r+dr,cc=c+dc;if(rr>=0&&rr<9&&cc>=0&&cc<9&&cells[rr*9+cc].mine)n++}cells[i].num=n}return cells}
function flood(board,idx){const q=[idx],opened=[];while(q.length){const i=q.shift(),x=board[i];if(!x||x.open||x.blocked||x.mine)continue;x.open=true;opened.push(i);if(x.num===0){const r=Math.floor(i/9),c=i%9;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const rr=r+dr,cc=c+dc,j=rr*9+cc;if(rr>=0&&rr<9&&cc>=0&&cc<9&&!board[j].open&&!board[j].blocked&&!board[j].mine)q.push(j)}}}return opened.length}
function safeLeft(b){return b.filter(x=>!x.mine&&!x.open).length}
function blockTen(board){const a=board.filter(x=>!x.mine&&!x.open&&!x.blocked);for(let i=0;i<10&&a.length;i++){const p=Math.floor(Math.random()*a.length);a[p].blocked=true;a.splice(p,1)}}
function unblockSome(board,n=10){const a=board.filter(x=>x.blocked);for(let i=0;i<n&&a.length;i++){const p=Math.floor(Math.random()*a.length);a[p].blocked=false;a.splice(p,1)}}
function addAttack(side){side.progress++;if(side.progress>=10){side.progress-=10;return 10}return 0}
function renderBoard(el,b,opp=false){el.innerHTML='';b.forEach((x,i)=>{const c=document.createElement('button');c.className='xpvp-cell'+(x.open?' open':'')+(x.blocked?' blocked':'');if(x.open)c.textContent=x.mine?'💥':(x.num||'');if(x.blocked)c.textContent='▦';if(!opp)c.onclick=()=>playerOpen(i);el.appendChild(c)})}
function ui(){const host=document.querySelector('#msoView');if(!host||!/^PvP$/i.test(host.querySelector('h2')?.textContent?.trim()||''))return; if(host.querySelector('#xpvpCard'))return;const s=norm(load());const card=document.createElement('div');card.id='xpvpCard';card.className='mso-card xpvp-wrap';card.innerHTML=`<h3>💥 익스트림 PvP</h3><p>안전칸을 <b>10칸 열 때마다 상대에게 방해칸 10개</b>를 보낸다. 상대도 10칸을 열면 똑같이 10칸을 보낸다.</p><div class="xpvp-top"><button class="mso-action primary" id="xpvpStart">익스트림 PvP 시작</button><span>기록 ${s.pvpExtreme.wins}승 ${s.pvpExtreme.losses}패</span><span>LP ${s.lp} · MMR ${s.mmr}</span></div><div id="xpvpGame" style="display:none"><div class="xpvp-score"><div class="xpvp-panel"><b>나</b><div>공격 게이지 <span id="xpvpMeGauge">0</span>/10</div><div class="xpvp-meter"><i id="xpvpMeBar" style="width:0%"></i></div><div id="xpvpMe" class="xpvp-board"></div></div><div class="xpvp-panel xpvp-opponent"><b>상대</b><div>공격 게이지 <span id="xpvpOpGauge">0</span>/10</div><div class="xpvp-meter"><i id="xpvpOpBar" style="width:0%"></i></div><div id="xpvpOp" class="xpvp-board"></div></div></div><div id="xpvpFeed" class="xpvp-feed"></div></div>`;host.appendChild(card);card.querySelector('#xpvpStart').onclick=start}
function update(){if(!match)return;const me=document.getElementById('xpvpMe'),op=document.getElementById('xpvpOp');if(!me||!op)return;renderBoard(me,match.me,false);renderBoard(op,match.op,true);document.getElementById('xpvpMeGauge').textContent=match.meProgress;document.getElementById('xpvpOpGauge').textContent=match.opProgress;document.getElementById('xpvpMeBar').style.width=(match.meProgress*10)+'%';document.getElementById('xpvpOpBar').style.width=(match.opProgress*10)+'%'}
function feed(t){const e=document.getElementById('xpvpFeed');if(e)e.textContent=t}
function start(){clearInterval(aiTimer);match={me:makeBoard(),op:makeBoard(),meProgress:0,opProgress:0,ended:false};document.getElementById('xpvpGame').style.display='block';feed('시작! 10칸마다 상대에게 10칸 공격.');update();aiTimer=setInterval(aiMove,850+Math.random()*550)}
function playerOpen(i){if(!match||match.ended)return;const x=match.me[i];if(!x||x.open||x.blocked)return;if(x.mine){x.open=true;finish(false,'지뢰를 밟았어.');update();return}let n=flood(match.me,i);for(let k=0;k<n;k++){match.meProgress++;if(match.meProgress>=10){match.meProgress-=10;blockTen(match.op);feed('💥 공격! 상대에게 방해칸 10개를 보냈어.')}}if(safeLeft(match.me)===0)finish(true,'내가 먼저 전부 열었어!');update()}
function aiMove(){if(!match||match.ended)return;const available=match.op.filter(x=>!x.mine&&!x.open&&!x.blocked);if(!available.length){unblockSome(match.op,10);update();return}const count=Math.random()<.28?2:1;for(let z=0;z<count;z++){const a=match.op.filter(x=>!x.mine&&!x.open&&!x.blocked);if(!a.length)break;const x=a[Math.floor(Math.random()*a.length)];const n=flood(match.op,x.i);for(let k=0;k<n;k++){match.opProgress++;if(match.opProgress>=10){match.opProgress-=10;blockTen(match.me);feed('⚠️ 상대 공격! 내 판에 방해칸 10개가 들어왔어.')}}}if(safeLeft(match.op)===0)finish(false,'상대가 먼저 전부 열었어.');update()}
function finish(win,msg){if(!match||match.ended)return;match.ended=true;clearInterval(aiTimer);const s=norm(load());if(win){s.pvpExtreme.wins++;s.pvp.wins=(s.pvp.wins||0)+1;s.lp+=3;s.mmr+=2;s.achievements??={};s.achievements.pvpWin=true}else{s.pvpExtreme.losses++;s.pvp.losses=(s.pvp.losses||0)+1;s.lp=Math.max(0,s.lp-2);s.mmr=Math.max(100,s.mmr-2)}save(s);feed(`${win?'🏆 승리':'💥 패배'} · ${msg} · LP ${win?'+3':'-2'} / MMR ${win?'+2':'-2'}`)}
// 기존 PvP 랭크 매치도 너무 빠르게 오르지 않게 가로채서 완만하게 적용
 document.addEventListener('click',e=>{const b=e.target.closest?.('[data-pvp="match"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const s=norm(load());const chance=0.5+(s.mmr-1000)/4000;const win=Math.random()<Math.max(.35,Math.min(.65,chance));if(win){s.pvp.wins++;s.lp+=3;s.mmr+=2;s.achievements??={};s.achievements.pvpWin=true}else{s.pvp.losses++;s.lp=Math.max(0,s.lp-2);s.mmr=Math.max(100,s.mmr-2)}save(s);const r=document.getElementById('msoPvpResult');if(r)r.innerHTML=`<p><b>${win?'승리':'패배'}</b> · LP ${win?'+3':'-2'} · MMR ${win?'+2':'-2'}</p>`;setTimeout(ui,0)},true);
style();const mo=new MutationObserver(()=>ui());mo.observe(document.body,{childList:true,subtree:true});setInterval(ui,700);
})();