(()=>{
'use strict';
const KEY='msSuiteV3';
let match=null,aiTimer=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(_){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('mso-state-changed'))}
function norm(s){s.lp=Number(s.lp||0);s.mmr=Number(s.mmr||1000);s.pvp??={wins:0,losses:0};s.pvpExtreme??={wins:0,losses:0};return s}
function style(){if(document.getElementById('xpvpStyle'))return;const x=document.createElement('style');x.id='xpvpStyle';x.textContent=`.xpvp-wrap{margin-top:14px}.xpvp-top{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:8px 0}.xpvp-score{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.xpvp-panel{border:1px solid #dbe3ec;border-radius:12px;background:#fff;padding:12px}.xpvp-board{display:grid;grid-template-columns:repeat(9,24px);gap:2px;width:max-content;max-width:100%;margin-top:8px}.xpvp-cell{width:24px;height:24px;padding:0;border:1px solid #b8c1cc;border-radius:3px;background:#dbe3ec;font-size:12px;font-weight:900;cursor:pointer}.xpvp-cell.open{background:#fff}.xpvp-cell.blocked{background:#111827;color:#fff}.xpvp-cell.mine{background:#ef4444;color:#fff}.xpvp-feed{margin-top:8px;min-height:22px;font-weight:800}.xpvp-meter{height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden}.xpvp-meter i{display:block;height:100%;background:#111827}.xpvp-opponent .xpvp-cell{pointer-events:none}.xpvp-mode{font-size:13px;color:#6b7280;margin-top:4px}@media(max-width:700px){.xpvp-score{grid-template-columns:1fr}.xpvp-board{grid-template-columns:repeat(9,22px)}.xpvp-cell{width:22px;height:22px}}`;document.head.appendChild(x)}
function makeBoard(){const cells=Array.from({length:81},(_,i)=>({mine:false,open:false,blocked:false,num:0,i}));const mines=[];while(mines.length<10){const n=Math.floor(Math.random()*81);if(!mines.includes(n))mines.push(n)}mines.forEach(i=>cells[i].mine=true);recount(cells);return cells}
function recount(cells){for(let i=0;i<81;i++){if(cells[i].mine){cells[i].num=0;continue}const r=Math.floor(i/9),c=i%9;let n=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const rr=r+dr,cc=c+dc;if(rr>=0&&rr<9&&cc>=0&&cc<9&&cells[rr*9+cc].mine)n++}cells[i].num=n}}
function makeFirstSafe(board,idx){if(!board[idx]?.mine)return;const repl=board.find(x=>!x.mine&&x.i!==idx&&!x.open);if(!repl)return;board[idx].mine=false;repl.mine=true;recount(board)}
function flood(board,idx){const q=[idx],opened=[];while(q.length){const i=q.shift(),x=board[i];if(!x||x.open||x.blocked||x.mine)continue;x.open=true;opened.push(i);if(x.num===0){const r=Math.floor(i/9),c=i%9;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const rr=r+dr,cc=c+dc,j=rr*9+cc;if(rr>=0&&rr<9&&cc>=0&&cc<9&&!board[j].open&&!board[j].blocked&&!board[j].mine)q.push(j)}}}return opened.length}
function safeLeft(b){return b.filter(x=>!x.mine&&!x.open).length}
function sendTen(board){const a=board.filter(x=>!x.mine&&!x.open&&!x.blocked);let n=0;while(n<10&&a.length){const p=Math.floor(Math.random()*a.length);a[p].blocked=true;a.splice(p,1);n++}return n}
function renderBoard(el,b,opp=false){el.innerHTML='';b.forEach((x,i)=>{const c=document.createElement('button');c.className='xpvp-cell'+(x.open?' open':'')+(x.blocked?' blocked':'')+(x.open&&x.mine?' mine':'');if(x.open)c.textContent=x.mine?'💥':(x.num||'');else if(x.blocked)c.textContent='▦';if(!opp)c.onclick=()=>playerOpen(i);el.appendChild(c)})}
function ui(){const host=document.querySelector('#msoView');if(!host||!/^PvP$/i.test(host.querySelector('h2')?.textContent?.trim()||''))return;if(host.querySelector('#xpvpCard'))return;const s=norm(load());const card=document.createElement('div');card.id='xpvpCard';card.className='mso-card xpvp-wrap';card.innerHTML=`<h3>⚔️ PvP 보드 대전</h3><p>이제 PvP는 랜덤 승패가 아니라 <b>실제 지뢰찾기 판</b>으로 진행돼.</p><div class="xpvp-top"><button class="mso-action primary" id="pvpNormalStart">일반 PvP 시작</button><button class="mso-action" id="xpvpStart">💥 익스트림 PvP 시작</button><span>LP ${s.lp} · MMR ${s.mmr}</span></div><div class="xpvp-mode">일반: 상대보다 먼저 판을 완료하면 승리 · 익스트림: 안전칸 10칸마다 상대에게 방해칸 10개 전송</div><div id="xpvpGame" style="display:none"><div class="xpvp-score"><div class="xpvp-panel"><b>나</b><div>남은 안전칸 <span id="xpvpMeLeft">71</span></div><div id="xpvpAttackMe" style="display:none">공격 게이지 <span id="xpvpMeGauge">0</span>/10<div class="xpvp-meter"><i id="xpvpMeBar" style="width:0%"></i></div></div><div id="xpvpMe" class="xpvp-board"></div></div><div class="xpvp-panel xpvp-opponent"><b>상대</b><div>남은 안전칸 <span id="xpvpOpLeft">71</span></div><div id="xpvpAttackOp" style="display:none">공격 게이지 <span id="xpvpOpGauge">0</span>/10<div class="xpvp-meter"><i id="xpvpOpBar" style="width:0%"></i></div></div><div id="xpvpOp" class="xpvp-board"></div></div></div><div id="xpvpFeed" class="xpvp-feed"></div></div>`;host.appendChild(card);card.querySelector('#pvpNormalStart').onclick=()=>start('normal');card.querySelector('#xpvpStart').onclick=()=>start('extreme')}
function update(){if(!match)return;const me=document.getElementById('xpvpMe'),op=document.getElementById('xpvpOp');if(!me||!op)return;renderBoard(me,match.me,false);renderBoard(op,match.op,true);document.getElementById('xpvpMeLeft').textContent=safeLeft(match.me);document.getElementById('xpvpOpLeft').textContent=safeLeft(match.op);const extreme=match.mode==='extreme';document.getElementById('xpvpAttackMe').style.display=extreme?'block':'none';document.getElementById('xpvpAttackOp').style.display=extreme?'block':'none';if(extreme){document.getElementById('xpvpMeGauge').textContent=match.meProgress;document.getElementById('xpvpOpGauge').textContent=match.opProgress;document.getElementById('xpvpMeBar').style.width=(match.meProgress*10)+'%';document.getElementById('xpvpOpBar').style.width=(match.opProgress*10)+'%'}}
function feed(t){const e=document.getElementById('xpvpFeed');if(e)e.textContent=t}
function start(mode){clearInterval(aiTimer);match={mode,me:makeBoard(),op:makeBoard(),meProgress:0,opProgress:0,ended:false,meFirst:true,opFirst:true};document.getElementById('xpvpGame').style.display='block';feed(mode==='extreme'?'💥 익스트림 시작! 10칸마다 상대에게 10칸을 보낸다.':'⚔️ 일반 PvP 시작! 상대보다 먼저 판을 완료해.');update();aiTimer=setInterval(aiMove,950)}
function attackFrom(side,target){if(match.mode!=='extreme')return;for(let k=0;k<side.opened;k++){side.progress++;if(side.progress>=10){side.progress-=10;const sent=sendTen(target);if(side.who==='me')feed(`💥 공격! 상대에게 방해칸 ${sent}개를 보냈어.`);else feed(`⚠️ 상대 공격! 내 판에 방해칸 ${sent}개가 들어왔어.`)}}}
function playerOpen(i){if(!match||match.ended)return;const x=match.me[i];if(!x||x.open)return;if(x.blocked){x.blocked=false;feed('▦ 방해칸 1개를 제거했어. 한 번 더 눌러 열 수 있어.');update();return}if(match.meFirst){makeFirstSafe(match.me,i);match.meFirst=false}if(match.me[i].mine){match.me[i].open=true;finish(false,'지뢰를 밟았어.');update();return}const n=flood(match.me,i);const side={who:'me',opened:n,progress:match.meProgress};attackFrom(side,match.op);match.meProgress=side.progress;if(safeLeft(match.me)===0)finish(true,'내가 먼저 판을 완료했어!');update()}
function aiMove(){if(!match||match.ended)return;let blocked=match.op.filter(x=>x.blocked&&!x.open);if(blocked.length&&Math.random()<.55){blocked[Math.floor(Math.random()*blocked.length)].blocked=false;feed('상대가 방해칸을 제거했어.');update();return}const a=match.op.filter(x=>!x.mine&&!x.open&&!x.blocked);if(!a.length)return;const x=a[Math.floor(Math.random()*a.length)];if(match.opFirst){makeFirstSafe(match.op,x.i);match.opFirst=false}const n=flood(match.op,x.i);const side={who:'op',opened:n,progress:match.opProgress};attackFrom(side,match.me);match.opProgress=side.progress;if(safeLeft(match.op)===0)finish(false,'상대가 먼저 판을 완료했어.');update()}
function finish(win,msg){if(!match||match.ended)return;match.ended=true;clearInterval(aiTimer);const s=norm(load());if(win){s.pvp.wins++;if(match.mode==='extreme')s.pvpExtreme.wins++;s.lp+=3;s.mmr+=2;s.achievements??={};s.achievements.pvpWin=true}else{s.pvp.losses++;if(match.mode==='extreme')s.pvpExtreme.losses++;s.lp=Math.max(0,s.lp-2);s.mmr=Math.max(100,s.mmr-2)}save(s);feed(`${win?'🏆 승리':'💥 패배'} · ${msg} · LP ${win?'+3':'-2'} / MMR ${win?'+2':'-2'}`)}
// 기존 '랭크 매치' 버튼도 랜덤 판정 대신 실제 일반 PvP 보드를 시작한다.
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-pvp="match"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();ui();setTimeout(()=>start('normal'),0)},true);
style();const mo=new MutationObserver(()=>ui());mo.observe(document.body,{childList:true,subtree:true});setInterval(ui,700);
})();