(()=>{
'use strict';
const KEY='msSuiteV3';
let match=null,aiTimer=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(_){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('mso-state-changed'))}
function norm(s){s.lp=Number(s.lp||0);s.mmr=Number(s.mmr||1000);s.pvp??={wins:0,losses:0};s.pvpExtreme??={wins:0,losses:0};return s}
function style(){if(document.getElementById('xpvpStyle'))return;const x=document.createElement('style');x.id='xpvpStyle';x.textContent=`
body.xpvp-page #gameView{display:none!important}
.xpvp-wrap{margin-top:14px}.xpvp-top{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:8px 0}.xpvp-score{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.xpvp-panel{border:1px solid #dbe3ec;border-radius:12px;background:#fff;padding:12px}.xpvp-board{display:grid;grid-template-columns:repeat(9,24px);gap:2px;width:max-content;max-width:100%;margin-top:8px}.xpvp-cell{width:24px;height:24px;padding:0;border:1px solid #b8c1cc;border-radius:3px;background:#dbe3ec;font-size:12px;font-weight:900;cursor:pointer}.xpvp-cell.open{background:#fff}.xpvp-cell.mine{background:#ef4444;color:#fff}.xpvp-cell.extra{background:#fef3c7;border-color:#f59e0b}.xpvp-cell.extra.open{background:#fff7ed;color:#92400e}.xpvp-feed{margin-top:8px;min-height:22px;font-weight:800}.xpvp-meter{height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden}.xpvp-meter i{display:block;height:100%;background:#111827}.xpvp-opponent .xpvp-cell{pointer-events:none}.xpvp-mode{font-size:13px;color:#6b7280;margin-top:4px}.xpvp-added{font-size:12px;color:#b45309;font-weight:800;margin-top:4px}@media(max-width:700px){.xpvp-score{grid-template-columns:1fr}.xpvp-board{grid-template-columns:repeat(9,22px)}.xpvp-cell{width:22px;height:22px}}`;
document.head.appendChild(x)}
function makeBoard(){const cells=Array.from({length:81},(_,i)=>({mine:false,open:false,num:0,i,extra:false,exploded:false}));const mines=[];while(mines.length<10){const n=Math.floor(Math.random()*81);if(!mines.includes(n))mines.push(n)}mines.forEach(i=>cells[i].mine=true);recount(cells);return cells}
function recount(cells){for(let i=0;i<81;i++){if(cells[i].mine){cells[i].num=0;continue}const r=Math.floor(i/9),c=i%9;let n=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const rr=r+dr,cc=c+dc;if(rr>=0&&rr<9&&cc>=0&&cc<9&&cells[rr*9+cc].mine)n++}cells[i].num=n}}
function makeFirstSafe(board,idx){if(!board[idx]?.mine)return;const repl=board.slice(0,81).find(x=>!x.mine&&x.i!==idx&&!x.open);if(!repl)return;board[idx].mine=false;repl.mine=true;recount(board)}
function flood(board,idx){const q=[idx],opened=[];while(q.length){const i=q.shift(),x=board[i];if(!x||x.open||x.mine||x.extra)continue;x.open=true;opened.push(i);if(x.num===0){const r=Math.floor(i/9),c=i%9;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const rr=r+dr,cc=c+dc,j=rr*9+cc;if(rr>=0&&rr<9&&cc>=0&&cc<9&&!board[j].open&&!board[j].mine)q.push(j)}}}return opened.length}
function extraLeft(b){return b.filter(x=>x.extra&&!x.open).length}
function safeLeft(b){return b.filter(x=>!x.mine&&!x.open).length}
function addTen(board){for(let n=0;n<10;n++)board.push({mine:false,open:false,num:0,i:board.length,extra:true,exploded:false});return 10}
function explodeNine(board,idx){const r=Math.floor(idx/9),c=idx%9;let opened=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const rr=r+dr,cc=c+dc;if(rr<0||rr>=9||cc<0||cc>=9)continue;const j=rr*9+cc,x=board[j];if(!x)continue;if(x.mine){x.open=true;x.exploded=true}else if(!x.open){x.open=true;opened++}}return opened}
function renderBoard(el,b,opp=false){el.innerHTML='';b.forEach((x,i)=>{const c=document.createElement('button');c.className='xpvp-cell'+(x.open?' open':'')+(x.open&&x.mine?' mine':'')+(x.extra?' extra':'');if(x.extra){c.textContent=x.open?'✓':'+'}else if(x.open)c.textContent=x.mine?'💥':(x.num||'');if(!opp)c.onclick=()=>playerOpen(i);el.appendChild(c)})}
function isPvpView(){const host=document.querySelector('#msoView');return !!host&&/^PvP$/i.test(host.querySelector('h2')?.textContent?.trim()||'')}
function enforcePvpVisibility(){if(isPvpView()){document.body.classList.add('xpvp-page');document.getElementById('gameView')?.classList.add('hidden')}else document.body.classList.remove('xpvp-page')}
function ui(){const host=document.querySelector('#msoView');if(!host||!isPvpView()){enforcePvpVisibility();return}enforcePvpVisibility();if(host.querySelector('#xpvpCard'))return;const s=norm(load());const old=host.querySelector('[data-pvp="match"]')?.closest('.mso-card');if(old)old.remove();const card=document.createElement('div');card.id='xpvpCard';card.className='mso-card xpvp-wrap';card.innerHTML=`<h3>⚔️ PvP 보드 대전</h3><div class="xpvp-top"><button class="mso-action primary" id="pvpNormalStart">일반 PvP 시작</button><button class="mso-action" id="xpvpStart">💥 익스트림 PvP 시작</button><span>LP ${s.lp} · MMR ${s.mmr}</span></div><div class="xpvp-mode">일반: 상대보다 먼저 완료 · 익스트림: 내가 10칸 해결할 때마다 상대가 해결해야 할 칸이 10칸 추가됨</div><div id="xpvpGame" style="display:none"><div class="xpvp-score"><div class="xpvp-panel"><b>나</b><div>남은 해결 칸 <span id="xpvpMeLeft">71</span></div><div class="xpvp-added">추가된 칸 <span id="xpvpMeExtra">0</span></div><div id="xpvpAttackMe" style="display:none">공격 게이지 <span id="xpvpMeGauge">0</span>/10<div class="xpvp-meter"><i id="xpvpMeBar" style="width:0%"></i></div></div><div id="xpvpMe" class="xpvp-board"></div></div><div class="xpvp-panel xpvp-opponent"><b>상대</b><div>남은 해결 칸 <span id="xpvpOpLeft">71</span></div><div class="xpvp-added">추가된 칸 <span id="xpvpOpExtra">0</span></div><div id="xpvpAttackOp" style="display:none">공격 게이지 <span id="xpvpOpGauge">0</span>/10<div class="xpvp-meter"><i id="xpvpOpBar" style="width:0%"></i></div></div><div id="xpvpOp" class="xpvp-board"></div></div></div><div id="xpvpFeed" class="xpvp-feed"></div></div>`;host.appendChild(card);card.querySelector('#pvpNormalStart').onclick=()=>start('normal');card.querySelector('#xpvpStart').onclick=()=>start('extreme')}
function update(){if(!match)return;const me=document.getElementById('xpvpMe'),op=document.getElementById('xpvpOp');if(!me||!op)return;renderBoard(me,match.me,false);renderBoard(op,match.op,true);document.getElementById('xpvpMeLeft').textContent=safeLeft(match.me);document.getElementById('xpvpOpLeft').textContent=safeLeft(match.op);document.getElementById('xpvpMeExtra').textContent=extraLeft(match.me);document.getElementById('xpvpOpExtra').textContent=extraLeft(match.op);const extreme=match.mode==='extreme';document.getElementById('xpvpAttackMe').style.display=extreme?'block':'none';document.getElementById('xpvpAttackOp').style.display=extreme?'block':'none';if(extreme){document.getElementById('xpvpMeGauge').textContent=match.meProgress;document.getElementById('xpvpOpGauge').textContent=match.opProgress;document.getElementById('xpvpMeBar').style.width=(match.meProgress*10)+'%';document.getElementById('xpvpOpBar').style.width=(match.opProgress*10)+'%'}}
function feed(t){const e=document.getElementById('xpvpFeed');if(e)e.textContent=t}
function start(mode){clearInterval(aiTimer);match={mode,me:makeBoard(),op:makeBoard(),meProgress:0,opProgress:0,ended:false,meFirst:true,opFirst:true};document.getElementById('xpvpGame').style.display='block';feed(mode==='extreme'?'💥 익스트림 시작! 10칸 해결할 때마다 상대의 해결 칸이 10칸 늘어나.':'⚔️ 일반 PvP 시작! 상대보다 먼저 판을 완료해.');update();scheduleAi()}
function scheduleAi(){clearInterval(aiTimer);const delay=match?.mode==='extreme'?3000:2700;aiTimer=setInterval(aiMove,delay)}
function attack(who,opened,target){if(match.mode!=='extreme')return;let key=who==='me'?'meProgress':'opProgress';match[key]+=opened;while(match[key]>=10){match[key]-=10;addTen(target);feed(who==='me'?'💥 공격! 상대가 해결해야 할 칸 +10!':'⚠️ 상대 공격! 내가 해결해야 할 칸 +10!')}}
function playerOpen(i){if(!match||match.ended)return;const x=match.me[i];if(!x||x.open)return;if(x.extra){x.open=true;attack('me',1,match.op);if(safeLeft(match.me)===0)finish(true,'내가 먼저 모든 칸을 해결했어!');update();return}if(match.meFirst){makeFirstSafe(match.me,i);match.meFirst=false}if(match.me[i].mine){explodeNine(match.me,i);feed('💥 지뢰! 주변 3×3 영역만 터졌어. 게임은 계속돼.');if(safeLeft(match.me)===0)finish(true,'폭발 뒤 남은 칸까지 모두 해결했어!');update();return}const n=flood(match.me,i);attack('me',n,match.op);if(safeLeft(match.me)===0)finish(true,'내가 먼저 모든 칸을 해결했어!');update()}
function aiMove(){if(!match||match.ended)return;const extras=match.op.filter(x=>x.extra&&!x.open);if(extras.length){extras[0].open=true;attack('op',1,match.me);if(safeLeft(match.op)===0)finish(false,'상대가 먼저 모든 칸을 해결했어.');update();return}const a=match.op.slice(0,81).filter(x=>!x.mine&&!x.open);if(!a.length){if(safeLeft(match.op)===0)finish(false,'상대가 먼저 모든 칸을 해결했어.');return}const x=a[Math.floor(Math.random()*a.length)];if(match.opFirst){makeFirstSafe(match.op,x.i);match.opFirst=false}const n=Math.min(flood(match.op,x.i),3);attack('op',n,match.me);if(safeLeft(match.op)===0)finish(false,'상대가 먼저 모든 칸을 해결했어.');update()}
function finish(win,msg){if(!match||match.ended)return;match.ended=true;clearInterval(aiTimer);const s=norm(load());if(win){s.pvp.wins++;if(match.mode==='extreme')s.pvpExtreme.wins++;s.lp+=3;s.mmr+=2;s.achievements??={};s.achievements.pvpWin=true}else{s.pvp.losses++;if(match.mode==='extreme')s.pvpExtreme.losses++;s.lp=Math.max(0,s.lp-2);s.mmr=Math.max(100,s.mmr-2)}save(s);feed(`${win?'🏆 승리':'💥 패배'} · ${msg} · LP ${win?'+3':'-2'} / MMR ${win?'+2':'-2'}`)}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-pvp="match"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();ui();setTimeout(()=>start('normal'),0)},true);
style();const mo=new MutationObserver(()=>{ui();enforcePvpVisibility()});mo.observe(document.body,{childList:true,subtree:true,classList:true});setInterval(()=>{ui();enforcePvpVisibility()},600);
})();