(()=>{
'use strict';
const KEY='msSuiteV2';
const TABS=['대시보드','트로피·계급','보석','퀘스트','업적','투기장','PvP','장비','재능','이벤트','통계·기록'];
const GEMS=[['ruby','🔻','루비'],['sapphire','🔵','사파이어'],['topaz','🟠','토파즈'],['amethyst','🟣','자수정'],['onyx','⚫','오닉스'],['aquamarine','💠','아쿠아마린'],['emerald','🟢','에메랄드'],['garnet','🔴','가넷'],['jade','🟢','제이드'],['diamond','💎','다이아몬드']];
const RANKS=[['Rookie',0],['Private',10],['Sergeant',25],['Lieutenant',50],['Captain',100],['Major',200],['Colonel',350],['General',550],['Marshal',800],['Grand Marshal',1100]];
const ARENA_TYPES=['Speed','Speed NG','No Flags','Efficiency','High Difficulty','Random Difficulty','Hardcore','Hardcore NG','Endurance','Nightmare'];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(_){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function state(){const s=load();s.trophies??=0;s.xp??=0;s.honour??=0;s.lp??=0;s.mmr??=1000;s.games??=0;s.wins??=0;s.bestEff??=0;s.bestTime??={};s.streak??=0;s.maxStreak??=0;s.eventPoints??=0;s.gems??={};s.achievements??={};s.talents??={points:0,equipped:[]};s.pvp??={wins:0,losses:0};s.history??=[];s.lastRewardKey??='';return s}
function rankName(t){let r=RANKS[0][0];for(const [n,v] of RANKS)if(t>=v)r=n;return r}
function league(lp){return lp>=600?'Grandmaster':lp>=500?'Master':lp>=400?'Platinum':lp>=300?'Gold':lp>=200?'Silver':lp>=100?'Bronze':'Iron'}
function dailyQuests(){return[{id:'q1',title:'게임 3판 클리어',goal:3,progress:0,reward:'트로피 +2'},{id:'q2',title:'효율 100% 이상 달성',goal:1,progress:0,reward:'재능 포인트 +1'},{id:'q3',title:'게임 10판 클리어',goal:10,progress:0,reward:'이벤트 점수 +20'}]}
function ensureDaily(s){const d=new Date().toISOString().slice(0,10);if(s.questDay!==d){s.questDay=d;s.quests=dailyQuests();save(s)}if(!Array.isArray(s.quests))s.quests=dailyQuests()}
function awardQuest(s,q){if(q.claimed||q.progress<q.goal)return;if(q.id==='q1')s.trophies+=2;if(q.id==='q2')s.talents.points++;if(q.id==='q3')s.eventPoints+=20;q.claimed=true}
function difficulty(){return document.getElementById('difficulty')?.value||'intermediate'}
function parseEff(){const t=document.getElementById('efficiency')?.textContent||'';const m=t.match(/([\d.]+)%/);return m?Number(m[1]):0}
function parseTime(){return Number(document.getElementById('timer')?.textContent||0)||0}
function recordWin(){const s=state();ensureDaily(s);const diff=difficulty(),eff=parseEff(),time=parseTime();const key=`${diff}:${time}:${eff}`;if(!time||s.lastRewardKey===key)return;s.lastRewardKey=key;s.games++;s.wins++;s.streak++;s.maxStreak=Math.max(s.maxStreak,s.streak);s.bestEff=Math.max(s.bestEff,eff);if(!s.bestTime[diff]||time<s.bestTime[diff])s.bestTime[diff]=time;const base=diff==='expert'?3:diff==='intermediate'?2:1;s.trophies+=base+(eff>=100?1:0);s.xp+=base*10;s.eventPoints+=base;s.talents.points+=s.wins%10===0?1:0;s.quests.forEach(q=>{if(q.id==='q1'||q.id==='q3')q.progress=Math.min(q.goal,q.progress+1);if(q.id==='q2'&&eff>=100)q.progress=1;awardQuest(s,q)});s.achievements.firstWin=true;if(s.streak>=10)s.achievements.streak10=true;if(eff>=100)s.achievements.eff100=true;s.history.unshift({at:Date.now(),diff,time,eff});s.history=s.history.slice(0,30);save(s);refreshOpen()}
function recordLoss(){const s=state();s.games++;s.streak=0;save(s);refreshOpen()}
const style=document.createElement('style');style.textContent=`.sidebar{overflow-y:auto}.mso-nav-label{padding:16px 14px 5px;color:#6b7280;font-size:11px;font-weight:900;letter-spacing:.08em}.mso-inline-view{display:none}.mso-inline-view.active{display:block}.mso-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.mso-card{background:white;border:1px solid #dbe3ec;border-radius:12px;padding:14px;margin-bottom:10px}.mso-card h3{margin:0 0 8px;font-size:15px}.mso-big{font-size:24px;font-weight:900}.mso-pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2ff;margin:2px;font-size:12px}.mso-progress{height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden;margin-top:6px}.mso-progress i{display:block;height:100%;background:#111827}.mso-action{border:1px solid #cbd5e1;background:#fff;border-radius:9px;padding:8px 11px;margin:4px;cursor:pointer;font-weight:800}.mso-action.primary{background:#111827;color:#fff}.mso-table{width:100%;border-collapse:collapse}.mso-table td,.mso-table th{padding:8px;border-bottom:1px solid #e5e7eb;text-align:left}@media(max-width:800px){.mso-nav-label{display:none}.sidebar{overflow-x:auto;overflow-y:hidden}}`;document.head.appendChild(style);
const sidebar=document.querySelector('.sidebar'),app=document.querySelector('.app');if(!sidebar||!app)return;const account=sidebar.querySelector('.account-mini');
const label=document.createElement('div');label.className='mso-nav-label';label.textContent='게임 시스템';sidebar.insertBefore(label,account||null);
const root=document.createElement('section');root.id='msoSuiteView';root.className='view-note mso-inline-view';root.innerHTML='<div id="msoView"></div>';app.appendChild(root);
const buttons=[];TABS.forEach((n,i)=>{const b=document.createElement('button');b.type='button';b.className='nav-item mso-nav-item';b.dataset.msoTab=i;b.textContent=n;sidebar.insertBefore(b,account||null);b.onclick=()=>openTab(i,b);buttons.push(b)});
function allBaseViews(){return['profileView','noguessView','marketView','authView','arenaView','onlineView','rankingView','equipmentView'].map(id=>document.getElementById(id)).filter(Boolean)}
function hideEverything(){document.getElementById('gameView')?.classList.add('hidden');allBaseViews().forEach(v=>v.classList.remove('active'));root.classList.remove('active')}
function enforceBoard(view){const g=document.getElementById('gameView');if(!g)return;const show=view==='game'||view==='noguess';g.classList.toggle('hidden',!show)}
function openTab(i,b){document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b?.classList.add('active');hideEverything();root.classList.add('active');root.dataset.tab=i;render(i)}
document.addEventListener('click',e=>{const b=e.target.closest?.('.nav-item');if(!b||b.classList.contains('mso-nav-item'))return;root.classList.remove('active');buttons.forEach(x=>x.classList.remove('active'));setTimeout(()=>enforceBoard(b.dataset.view),0)},true);
function gotoBase(view){const b=[...document.querySelectorAll('.nav-item:not(.mso-nav-item)')].find(x=>x.dataset.view===view);if(b)b.click()}
function wallet(s){return`<div class="mso-grid"><div class="mso-card"><h3>⭐ 트로피</h3><div class="mso-big">${s.trophies}</div></div><div class="mso-card"><h3>🎖 계급</h3><div class="mso-big">${rankName(s.trophies)}</div></div><div class="mso-card"><h3>⚔️ PvP</h3><div class="mso-big">${league(s.lp)} ${s.lp} LP</div></div><div class="mso-card"><h3>🔥 최고 연승</h3><div class="mso-big">${s.maxStreak}</div></div></div>`}
function render(i){const v=root.querySelector('#msoView'),s=state();ensureDaily(s);
if(i===0)v.innerHTML=`<h2>대시보드</h2>${wallet(s)}<div class="mso-grid"><div class="mso-card"><h3>게임</h3><b>${s.wins}승 / ${s.games}판</b></div><div class="mso-card"><h3>최고 효율</h3><b>${s.bestEff.toFixed(1)}%</b></div><div class="mso-card"><h3>재능 포인트</h3><b>${s.talents.points}</b></div><div class="mso-card"><h3>이벤트 점수</h3><b>${s.eventPoints}</b></div></div>`;
if(i===1){const n=RANKS.find(x=>x[1]>s.trophies);v.innerHTML=`<h2>트로피 · 계급</h2>${wallet(s)}<div class="mso-card">${n?`다음 계급 ${n[0]}까지 ${Math.max(0,n[1]-s.trophies)} 트로피`:'최고 계급 달성'}</div>`}
if(i===2)v.innerHTML=`<h2>보석</h2><div class="mso-grid">${GEMS.map(([k,e,n])=>`<div class="mso-card"><h3>${e} ${n}</h3><div class="mso-big">${Number(s.gems[k]||0)}</div></div>`).join('')}</div>`;
if(i===3)v.innerHTML=`<h2>퀘스트</h2>${s.quests.map(q=>`<div class="mso-card"><b>${q.title}</b><div>${q.progress}/${q.goal} ${q.claimed?'✅ 완료':''}</div><div class="mso-progress"><i style="width:${Math.min(100,q.progress/q.goal*100)}%"></i></div><small>${q.reward}</small></div>`).join('')}`;
if(i===4){const a=[['firstWin','첫 승리','게임 1판 클리어'],['streak10','연승 10','10연승 달성'],['eff100','효율 100','효율 100% 이상'],['arena8','투기장 정복','L8 투기장 성공'],['pvpWin','PvP 승리','PvP 첫 승']];v.innerHTML=`<h2>업적</h2><div class="mso-grid">${a.map(([k,n,d])=>`<div class="mso-card"><h3>${s.achievements[k]?'✅':'⬜'} ${n}</h3>${d}</div>`).join('')}</div>`}
if(i===5)v.innerHTML=`<h2>투기장</h2><button class="mso-action primary" data-go="arena">기존 투기장 열기</button><div class="mso-grid">${ARENA_TYPES.map(t=>`<div class="mso-card"><h3>${t}</h3>${[1,2,3,4,5,6,7,8].map(l=>`<span class="mso-pill">L${l}</span>`).join('')}</div>`).join('')}</div>`;
if(i===6)v.innerHTML=`<h2>PvP</h2>${wallet(s)}<div class="mso-card"><h3>랭크 연습 매치</h3><p>현재는 로컬 연습 매치로 LP/MMR 흐름을 시험할 수 있어.</p><button class="mso-action primary" data-pvp="win">승리 처리</button><button class="mso-action" data-pvp="lose">패배 처리</button><div>${s.pvp.wins}승 ${s.pvp.losses}패 · MMR ${s.mmr}</div></div>`;
if(i===7)v.innerHTML=`<h2>장비</h2><button class="mso-action primary" data-go="equipment">기존 장비 화면 열기</button><div class="mso-card">엔진 · 선체 · 어뢰 · 레이더 · 소나의 제작/강화/장착 시스템은 기존 장비 화면과 연결돼.</div>`;
if(i===8)v.innerHTML=`<h2>재능</h2><div class="mso-card"><h3>재능 포인트</h3><div class="mso-big">${s.talents.points}</div><button class="mso-action" data-talent="eff">효율 재능 장착</button><button class="mso-action" data-talent="reward">보상 재능 장착</button><div>장착: ${s.talents.equipped.join(', ')||'없음'}</div></div>`;
if(i===9)v.innerHTML=`<h2>이벤트</h2><div class="mso-card"><h3>이벤트 점수</h3><div class="mso-big">${s.eventPoints}</div><p>게임을 클리어하면 난이도에 따라 이벤트 점수가 올라가.</p></div>`;
if(i===10)v.innerHTML=`<h2>통계 · 기록</h2><div class="mso-grid"><div class="mso-card"><h3>총 게임</h3><div class="mso-big">${s.games}</div></div><div class="mso-card"><h3>최고 효율</h3><div class="mso-big">${s.bestEff.toFixed(1)}%</div></div><div class="mso-card"><h3>최고 연승</h3><div class="mso-big">${s.maxStreak}</div></div></div><table class="mso-table"><thead><tr><th>난이도</th><th>시간</th><th>효율</th></tr></thead><tbody>${s.history.map(h=>`<tr><td>${h.diff}</td><td>${h.time}s</td><td>${h.eff.toFixed(1)}%</td></tr>`).join('')||'<tr><td colspan="3">기록 없음</td></tr>'}</tbody></table>`;
}
root.addEventListener('click',e=>{const go=e.target.dataset.go;if(go){gotoBase(go);return}const p=e.target.dataset.pvp;if(p){const s=state();if(p==='win'){s.pvp.wins++;s.lp+=20;s.mmr+=15;s.trophies++;s.achievements.pvpWin=true}else{s.pvp.losses++;s.lp=Math.max(0,s.lp-12);s.mmr=Math.max(0,s.mmr-10)}save(s);render(6);return}const t=e.target.dataset.talent;if(t){const s=state();const name=t==='eff'?'효율':'보상';if(!s.talents.equipped.includes(name)){if(s.talents.points<1)return alert('재능 포인트가 부족해.');s.talents.points--;s.talents.equipped.push(name);save(s)}render(8)}});
let lastMsg='';new MutationObserver(()=>{const m=document.getElementById('msg')?.textContent||'';if(m===lastMsg)return;lastMsg=m;if(/클리어|clear/i.test(m))setTimeout(recordWin,50);else if(/게임 오버|game over/i.test(m))recordLoss()}).observe(document.body,{subtree:true,childList:true,characterData:true});
function refreshOpen(){if(root.classList.contains('active'))render(Number(root.dataset.tab||0))}
window.MinesweeperSuite={state,save,render,open:()=>openTab(0,buttons[0])};
})();