(()=>{
'use strict';
const KEY='msSuiteV1';
const ARENA_TYPES=['Speed','Speed NG','No Flags','Efficiency','High Difficulty','Random Difficulty','Hardcore','Hardcore NG','Endurance','Nightmare'];
const GEMS=[['ruby','🔻','루비'],['sapphire','🔵','사파이어'],['topaz','🟠','토파즈'],['amethyst','🟣','자수정'],['onyx','⚫','오닉스'],['aquamarine','💠','아쿠아마린'],['emerald','🌵','에메랄드'],['garnet','🔴','가넷'],['jade','🟢','제이드'],['diamond','💎','다이아몬드']];
const RANKS=[['Rookie',0],['Private',10],['Sergeant',25],['Lieutenant',50],['Captain',100],['Major',200],['Colonel',350],['General',550],['Marshal',800],['Grand Marshal',1100]];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(_){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function state(){const s=load();s.trophies??=0;s.xp??=0;s.honour??=0;s.lp??=0;s.mmr??=1000;s.activity??=0;s.eventPoints??=0;s.questStreak??=0;s.dailyLogin??=0;s.gems??={};s.achievements??={};s.talents??={points:0,equipped:[]};s.quests??=[];s.seasonQuests??=[];s.pvp??={wins:0,losses:0};s.arenaBest??={};return s}
function rankName(t){let r=RANKS[0][0];for(const [n,v] of RANKS)if(t>=v)r=n;return r}
function league(lp){return lp>=600?'Grandmaster':lp>=500?'Master':lp>=400?'Platinum':lp>=300?'Gold':lp>=200?'Silver':lp>=100?'Bronze':'Iron'}
function esc(x){return String(x??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function makeQuests(){return [
 {id:'q1',title:'게임 3판 클리어',goal:3,progress:0,reward:'코인 +50'},
 {id:'q2',title:'깃발 없이 1판 클리어',goal:1,progress:0,reward:'보석 확률 보너스'},
 {id:'q3',title:'효율 100% 이상 달성',goal:1,progress:0,reward:'투기장 티켓 +1'}
]}
function ensureQuests(s){const day=new Date().toISOString().slice(0,10);if(s.questDay!==day){s.questDay=day;s.quests=makeQuests();save(s)}}
const style=document.createElement('style');
style.textContent=`#msoSuiteBtn{position:fixed;right:14px;bottom:14px;z-index:9998;border:0;border-radius:999px;padding:12px 16px;background:#111827;color:white;font-weight:800;cursor:pointer;box-shadow:0 8px 24px #0003}#msoSuite{position:fixed;inset:4vh 3vw;z-index:9999;background:#f8fafc;border:1px solid #cbd5e1;border-radius:18px;box-shadow:0 30px 80px #0006;display:none;overflow:hidden;font-family:system-ui,sans-serif}#msoSuite.open{display:grid;grid-template-columns:220px 1fr}.mso-side{background:#0f172a;color:white;padding:18px;overflow:auto}.mso-side h2{font-size:18px;margin:0 0 12px}.mso-tab{display:block;width:100%;text-align:left;padding:9px 10px;margin:4px 0;border:0;border-radius:8px;background:transparent;color:#e2e8f0;cursor:pointer}.mso-tab.active,.mso-tab:hover{background:#334155}.mso-main{padding:20px;overflow:auto}.mso-close{float:right;border:0;background:#e2e8f0;border-radius:8px;padding:7px 10px;cursor:pointer}.mso-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.mso-card{background:white;border:1px solid #dbe3ec;border-radius:12px;padding:14px}.mso-card h3{margin:0 0 8px;font-size:15px}.mso-big{font-size:24px;font-weight:900}.mso-pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2ff;margin:2px;font-size:12px}.mso-progress{height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden}.mso-progress i{display:block;height:100%;background:#111827}.mso-btn{border:1px solid #cbd5e1;background:white;border-radius:8px;padding:7px 10px;cursor:pointer;font-weight:700}.mso-table{width:100%;border-collapse:collapse}.mso-table td,.mso-table th{border-bottom:1px solid #e2e8f0;padding:8px;text-align:left}@media(max-width:700px){#msoSuite.open{grid-template-columns:1fr}.mso-side{display:flex;gap:4px;overflow:auto}.mso-side h2{display:none}.mso-tab{white-space:nowrap;width:auto}.mso-main{padding:12px}}`;
document.head.appendChild(style);
const btn=document.createElement('button');btn.id='msoSuiteBtn';btn.textContent='⭐ 게임 시스템';document.body.appendChild(btn);
const root=document.createElement('section');root.id='msoSuite';root.innerHTML=`<aside class="mso-side"><h2>게임 시스템</h2>${['대시보드','트로피·계급','보석','퀘스트','업적','투기장','PvP','장비','재능','이벤트','통계·기록'].map((x,i)=>`<button class="mso-tab${i===0?' active':''}" data-tab="${i}">${x}</button>`).join('')}</aside><main class="mso-main"><button class="mso-close">닫기 ✕</button><div id="msoView"></div></main>`;document.body.appendChild(root);
btn.onclick=()=>{root.classList.add('open');render(0)};root.querySelector('.mso-close').onclick=()=>root.classList.remove('open');root.querySelectorAll('.mso-tab').forEach((b,i)=>b.onclick=()=>render(i));
function walletHtml(){let s=state();return `<div class="mso-grid"><div class="mso-card"><h3>⭐ 트로피</h3><div class="mso-big">${s.trophies.toLocaleString()}</div></div><div class="mso-card"><h3>🎖 계급</h3><div class="mso-big">${rankName(s.trophies)}</div></div><div class="mso-card"><h3>⚔️ PvP</h3><div class="mso-big">${league(s.lp)} ${s.lp} LP</div></div><div class="mso-card"><h3>🏅 명예</h3><div class="mso-big">${s.honour.toLocaleString()}</div></div></div>`}
function render(i){root.querySelectorAll('.mso-tab').forEach((b,j)=>b.classList.toggle('active',i===j));const v=root.querySelector('#msoView'),s=state();ensureQuests(s);if(i===0)v.innerHTML=`<h1>대시보드</h1>${walletHtml()}<p>게임·투기장·PvP·퀘스트·장비·재능·이벤트를 한 화면에서 관리하는 통합 시스템이야.</p>`;
if(i===1){const next=RANKS.find(x=>x[1]>s.trophies);v.innerHTML=`<h1>트로피 · 계급</h1>${walletHtml()}<div class="mso-card"><h3>다음 계급</h3>${next?`${next[0]} · ${next[1]} 트로피 필요<div class="mso-progress"><i style="width:${Math.min(100,s.trophies/next[1]*100)}%"></i></div>`:'최고 계급 달성'}</div><div class="mso-card"><h3>트로피 종류</h3><span class="mso-pill">속도</span><span class="mso-pill">효율</span><span class="mso-pill">연승</span><span class="mso-pill">난이도</span><span class="mso-pill">투기장</span><span class="mso-pill">PvP</span><span class="mso-pill">퀘스트</span><span class="mso-pill">업적</span><span class="mso-pill">이벤트</span><span class="mso-pill">장비</span></div>`}
if(i===2)v.innerHTML=`<h1>보석</h1><div class="mso-grid">${GEMS.map(([k,e,n])=>`<div class="mso-card"><h3>${e} ${n}</h3><div class="mso-big">${Number(s.gems[k]||0).toLocaleString()}</div></div>`).join('')}</div>`;
if(i===3)v.innerHTML=`<h1>퀘스트</h1><h2>일일 퀘스트</h2>${s.quests.map(q=>`<div class="mso-card"><b>${esc(q.title)}</b><div>${q.progress}/${q.goal}</div><div class="mso-progress"><i style="width:${Math.min(100,q.progress/q.goal*100)}%"></i></div><small>${esc(q.reward)}</small></div>`).join('')}<h2>시즌 퀘스트</h2><div class="mso-card">시즌 퀘스트 슬롯 · 장비와 재능 보너스로 추가 슬롯 확장</div>`;
if(i===4){const a=[['첫 승리','게임 1판 클리어'],['연승 10','10연승 달성'],['효율 100','효율 100% 이상'],['투기장 정복','L8 투기장 성공'],['보석 수집가','10종 보석 획득'],['PvP 승리','PvP 첫 승']];v.innerHTML=`<h1>업적</h1><div class="mso-grid">${a.map(([n,d],j)=>`<div class="mso-card"><h3>${s.achievements[j]?'✅':'⬜'} ${n}</h3><div>${d}</div></div>`).join('')}</div>`}
if(i===5)v.innerHTML=`<h1>투기장</h1><p>10가지 유형 × 8레벨 구조</p><div class="mso-grid">${ARENA_TYPES.map(t=>`<div class="mso-card"><h3>⚔️ ${t}</h3><div>${[1,2,3,4,5,6,7,8].map(l=>`<span class="mso-pill">L${l}</span>`).join('')}</div></div>`).join('')}</div>`;
if(i===6)v.innerHTML=`<h1>PvP</h1>${walletHtml()}<div class="mso-grid"><div class="mso-card"><h3>랭크</h3><div class="mso-big">${league(s.lp)}</div><div>${s.lp} LP · MMR ${s.mmr}</div></div><div class="mso-card"><h3>전적</h3><div>${s.pvp.wins}승 ${s.pvp.losses}패</div></div><div class="mso-card"><h3>모드</h3><div>랭크 매칭 · 친구 로비 · 시즌 배치 · 시즌 보상</div></div></div>`;
if(i===7)v.innerHTML=`<h1>장비</h1><div class="mso-grid">${[['⚙️','엔진','일일 퀘스트'],['🛡️','선체','시즌 퀘스트'],['🚀','어뢰','활동'],['📡','레이더','이벤트 점수'],['🔊','소나','투기장 코인']].map(x=>`<div class="mso-card"><h3>${x[0]} ${x[1]}</h3><div>고유 효과: ${x[2]}</div><div>제작 · 강화 · 분해 · 시리즈 보너스</div></div>`).join('')}</div>`;
if(i===8)v.innerHTML=`<h1>재능</h1><div class="mso-card"><h3>재능 포인트</h3><div class="mso-big">${s.talents.points}</div></div><div class="mso-grid">${['Disciple','Improvisor','Strategist','Dreamer','Catalyst','Minimalist','Optimizer','Tactician','Scholar','Destroyer','Pacifist','Commander','Synergy','Awakening','Blessing'].map(x=>`<div class="mso-card"><h3>${x}</h3><div>일반/희귀/유니크/전설/신화 · 품질/접두 옵션 · 장착 슬롯</div></div>`).join('')}</div><div class="mso-card"><h3>천장(Mercy)</h3><div>Unique 10 · Legendary 30 · Mythic 100</div></div>`;
if(i===9)v.innerHTML=`<h1>월간 이벤트</h1><div class="mso-grid"><div class="mso-card"><h3>이벤트 점수</h3><div class="mso-big">${s.eventPoints.toLocaleString()}</div></div><div class="mso-card"><h3>이벤트 상점</h3><div>보석 · 투기장 티켓 · 장비</div></div><div class="mso-card"><h3>챔피언십</h3><div>속도 · 효율 등 월별 테마 랭킹</div></div><div class="mso-card"><h3>글로벌 퀘스트</h3><div>시간 제한형 공동 목표</div></div></div>`;
if(i===10)v.innerHTML=`<h1>통계 · 기록</h1><div class="mso-grid"><div class="mso-card"><h3>기록 지표</h3><div>시간 · 효율 · 3BV · 3BV/s · 클릭 · 깃발 · 연승 · 난이도</div></div><div class="mso-card"><h3>리더보드</h3><div>전체 · 시즌 · PvP · 이벤트 · 투기장 · 효율</div></div><div class="mso-card"><h3>관전/리플레이</h3><div>온라인 플레이어 관전과 기록 재생용 슬롯</div></div></div>`}
window.MinesweeperSuite={state,save,render,open:()=>{root.classList.add('open');render(0)}};
})();